### ISSUE TITLE
Player Movement: ultimate polishing

### ISSUE THREAD

**Issue by azazellus** [VDP-noclip/noclip#54]
The controller works well, but..................

Necessary things to fix:
- Increasing the drag also prevents the player to reach the maximum speed. Right now it's not possible to have a responsive control and reach the run speed. (If the speed is set to 8 and the drag set to 12, your maximum speed will be around 7, instead of 8);
- The keys to control the vertical movement in NoclipMode should be absolute instead of relative (WASD --> relative. QE --> absolute).

Less urgent:
- Since you remain attached to the slope as long as you keep the movement key pressed, when you press and quick release the same key at the top of the slope you jump a little. This isn't that problematic and maybe could be fixed by simply increasing the drag.

**Comment by stefanofossati** [comment]
Now the absolute vertical movement of the noclip camera shound be fixed.

I worry about the drag problem. The reality player controller is moved by a Force that has the speed variable, after that there is a check in order to avoid the exiding of the speed. With the frag the rigidbody has a inverse force to the movement. So the only thing that you can do now is to increase the speed

**Comment by TizioMaurizio** [comment]
you wanted the bike of rigid body? now you pedal ahahahahah jokes aside if we really wanted the control to be that responsive when walking we could have used the rigid body only when flying or on very slopes.  
Anyway what would happen by lowering the drag when a player is pressing movement buttons like we do for staying attached to slopes? bad things i guess but maybe it's worth trying
Everyone probably knows it by now but the main problem comes from the fact that drag is generic and without direction, it stands also for jumping, you jump lower if you don't lower it, that's why i say "bad things" but keeping this fact in mind we can possibly find a way to exploit it
